#!/usr/bin/env python3
"""Generate the native M11 institutional release contract."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from macro_sim.controllers.observation import DEFAULT_OBSERVATION_SPEC


JSON_PATH = ROOT / "schemas" / "m11" / "observation_contract.json"
CPP_PATH = (
    ROOT
    / "native"
    / "include"
    / "macro_sim"
    / "control"
    / "generated_m11_observation_contract.inc"
)


def canonical_json(value: Any) -> str:
    return json.dumps(
        value,
        allow_nan=False,
        ensure_ascii=True,
        separators=(",", ":"),
        sort_keys=True,
    )


def contract() -> tuple[str, str, str]:
    rows = [
        field.to_dict()
        for field in DEFAULT_OBSERVATION_SPEC.ordered_fields()
    ]
    body = {
        "schema_version": DEFAULT_OBSERVATION_SPEC.schema_version,
        "field_count": len(rows),
        "rows": rows,
    }
    semantic = canonical_json(body)
    digest = hashlib.sha256(semantic.encode("utf-8")).hexdigest()
    body["semantic_sha256"] = digest
    json_output = canonical_json(body) + "\n"

    lines = [
        "// Generated by tools/m11/generate_observation_contract.py; do not edit.",
        f'inline constexpr std::string_view kM11ObservationContractSha256 = "{digest}";',
        "inline constexpr std::array<M11ObservationFieldDescriptor, "
        f"{len(rows)}> kM11ObservationFields{{{{",
    ]
    for row in rows:
        access = (
            "public_access"
            if row["access_class"] == "public"
            else row["access_class"]
        )
        scale = (
            "std::nullopt"
            if row["normalization_scale"] is None
            else "std::optional<double>{"
            f"{float(row['normalization_scale']):.17g}"
            "}"
        )
        lines.append(
            "    {"
            + ", ".join(
                (
                    json.dumps(row["series_id"]),
                    json.dumps(row["source_key"]),
                    f"M11ObservationSource::{row['source']}",
                    f"M11ReleaseAggregation::{row['aggregation']}",
                    f"{row['window_ticks']}U",
                    f"{row['frequency_ticks']}U",
                    f"{row['publication_lag_ticks']}U",
                    f"{row['phase_offset_ticks']}U",
                    f"M11ReleaseAccess::{access}",
                    json.dumps("|".join(row["roles"])),
                    "true" if row["require_full_window"] else "false",
                    "true" if row["economy_indexed"] else "false",
                    scale,
                    json.dumps(row["unit"]),
                )
            )
            + "},"
        )
    lines.extend(("}};", ""))
    return json_output, "\n".join(lines), digest


def write_or_check(check: bool) -> int:
    json_output, cpp_output, _digest = contract()
    outputs = ((JSON_PATH, json_output), (CPP_PATH, cpp_output))
    if check:
        stale = [
            str(path.relative_to(ROOT))
            for path, content in outputs
            if not path.exists() or path.read_text() != content
        ]
        if stale:
            raise SystemExit(
                "stale M11 observation contract: " + ", ".join(stale)
            )
        return 0
    for path, content in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    return write_or_check(args.check)


if __name__ == "__main__":
    raise SystemExit(main())
