"""Deterministic replay by reinjecting canonical input events only."""
from __future__ import annotations

import pickle
from typing import Any, Iterable

from .occupants import RLOccupant, occupant_from_spec
from .protocol import PolicyAction, PolicyProposal, canonical_json
from .session import (
    AWAITING_HUMAN,
    BOUNDARY_START,
    ControlledSimulationSession,
)


def proposal_from_event(event: dict[str, Any]) -> PolicyProposal:
    raw = event.get("payload", {}).get("proposal")
    if not isinstance(raw, dict):
        raise ValueError("proposal input event has no canonical proposal payload")
    return PolicyProposal(
        proposal_id=raw["proposal_id"],
        idempotency_key=raw["idempotency_key"],
        context_id=raw["context_id"],
        actions=tuple(
            PolicyAction(action["lever"], action.get("value"))
            for action in raw.get("actions", ())
        ),
        reason=raw.get("reason", ""),
        based_on_policy_versions=raw.get("based_on_policy_versions", {}),
        supersedes_proposal_id=raw.get("supersedes_proposal_id"),
        schema_version=raw.get("schema_version", 1),
    )


def _require_next_input(
    session: ControlledSimulationSession,
    event: dict[str, Any],
) -> None:
    """Require derived regeneration to have reached this exact tape position."""
    expected_sequence = int(event["global_sequence"])
    if len(session.events.events) != expected_sequence:
        raise ValueError(
            "replay phase/order mismatch before input "
            f"{event.get('event_id', expected_sequence)}: event stream is at "
            f"{len(session.events.events)}"
        )
    if int(event["boundary_tick"]) != session.boundary_tick:
        raise ValueError("replay input boundary does not match the session boundary")
    if event["phase"] != session.phase:
        raise ValueError(
            f"replay input phase {event['phase']!r} does not match {session.phase!r}"
        )


def _assert_input_regenerated(
    session: ControlledSimulationSession,
    event: dict[str, Any],
) -> None:
    sequence = int(event["global_sequence"])
    if sequence >= len(session.events.events):
        raise ValueError(
            f"replay did not regenerate input {event.get('event_id', sequence)}"
        )
    actual = session.events.events[sequence]
    if canonical_json(actual) != canonical_json(event):
        raise ValueError(
            f"replayed input differs at global_sequence {sequence}"
        )


def _assign_from_event(
    session: ControlledSimulationSession,
    event: dict[str, Any],
) -> None:
    payload = event.get("payload", {})
    initialization = payload.get("initialization", "fresh")
    if str(initialization).startswith("restore:"):
        archived_id = str(initialization).split(":", 1)[1]
        occupant = session.assignment_archive[archived_id]
    else:
        occupant = occupant_from_spec(payload["occupant_spec"])
    session.assign_seat(
        int(event["economy_id"]),
        str(event["seat"]),
        occupant,
        actor=event.get("actor", "replay"),
        initialization=initialization,
    )


def _inject_immediate(
    session: ControlledSimulationSession,
    event: dict[str, Any],
) -> None:
    """Inject an input whose public call appends its event immediately."""
    _require_next_input(session, event)
    kind = event["event_type"]
    if kind == "seat_assignment":
        _assign_from_event(session, event)
    elif kind == "pending_cancel_requested":
        session.cancel_pending(
            str(event["decision_id"]), actor=event.get("actor", "replay")
        )
    elif kind == "human_proposal_queued":
        session.submit_human_proposal(
            proposal_from_event(event), actor=event.get("actor", "human")
        )
    elif kind == "timeout":
        context_id = event.get("context_id")
        if not isinstance(context_id, str) or not context_id:
            raise ValueError("timeout input has no context_id")
        session.timeout_context(
            context_id, actor=event.get("actor", "server_timeout")
        )
    elif kind == "proposal_submitted":
        origin = event.get("payload", {}).get("input_origin", "direct")
        if origin == "automatic":
            raise ValueError("automatic proposal input must be regenerated by advance")
        session.coordinator.submit(
            session,
            proposal_from_event(event),
            actor=event.get("actor", "controller"),
            input_event_type="proposal_submitted",
            input_origin=str(origin),
        )
    else:
        raise ValueError(
            f"input event {kind!r} cannot be injected immediately during replay"
        )
    _assert_input_regenerated(session, event)


def _is_automatic_input(event: dict[str, Any]) -> bool:
    return event.get("event_type") == "proposal_submitted" and (
        event.get("payload", {}).get("input_origin") == "automatic"
    )


def _seed_recorded_rl_proposals(
    session: ControlledSimulationSession,
    events: list[dict[str, Any]],
) -> int:
    """Privately seed inert RL placeholders from later automatic tape inputs.

    A live RL occupant produces and records its proposal while the boundary is
    opening. Its replay placeholder has no model, so the tape privately seeds the
    proposal before the same opening operation. Seeding itself appends no event;
    normal collection regenerates ``proposal_submitted`` at the source sequence.
    """
    if session.phase not in {BOUNDARY_START, AWAITING_HUMAN}:
        return 0
    inserted = 0
    missing = set(session.missing_context_ids)
    for event in events:
        if not _is_automatic_input(event):
            continue
        if int(event["boundary_tick"]) != session.boundary_tick:
            continue
        if event.get("phase") != session.phase:
            continue
        proposal = proposal_from_event(event)
        if session.phase == AWAITING_HUMAN:
            if proposal.context_id not in missing:
                continue
            context = session._opened_contexts.get(proposal.context_id)
            if context is None:
                raise ValueError(
                    "recorded RL proposal references an unopened context"
                )
            assignment_key = (context.economy_id, context.seat)
        else:
            economy_id = event.get("economy_id")
            seat = event.get("seat")
            if isinstance(economy_id, bool) or not isinstance(economy_id, int) \
                    or not isinstance(seat, str) or not seat:
                raise ValueError("recorded RL proposal seat metadata is malformed")
            assignment_key = (economy_id, seat)
        occupant = session.seat_assignments.get(assignment_key)
        if not isinstance(occupant, RLOccupant) or occupant.policy is not None:
            continue
        actor = event.get("actor", "RLOccupant")
        if not isinstance(actor, str) or not actor.strip():
            raise ValueError("recorded RL proposal actor is malformed")
        if occupant.seed_recorded_proposal(proposal, actor=actor):
            inserted += 1
    return inserted


def _check_expected_suffix(
    session: ControlledSimulationSession,
    expected: list[dict[str, Any]] | None,
    start: int,
) -> None:
    if expected is None:
        return
    if len(session.events.events) > len(expected):
        raise ValueError("replay generated events beyond the expected source tape")
    for sequence in range(start, len(session.events.events)):
        if canonical_json(session.events.events[sequence]) != canonical_json(
            expected[sequence]
        ):
            raise ValueError(
                f"replayed event differs at global_sequence {sequence}"
            )


def _skip_regenerated_inputs(
    session: ControlledSimulationSession,
    tick_inputs: list[dict[str, Any]],
    index: int,
) -> int:
    while index < len(tick_inputs) and int(
        tick_inputs[index]["global_sequence"]
    ) < len(session.events.events):
        _assert_input_regenerated(session, tick_inputs[index])
        index += 1
    return index


def _input_is_injectable_now(
    session: ControlledSimulationSession,
    event: dict[str, Any],
) -> bool:
    return (
        int(event["global_sequence"]) == len(session.events.events)
        and event.get("phase") == session.phase
        and not _is_automatic_input(event)
    )


def _drive_advancing_boundary(
    session: ControlledSimulationSession,
    tick_inputs: list[dict[str, Any]],
    expected: list[dict[str, Any]] | None,
) -> None:
    """Regenerate one complete engine boundary from ordered input positions."""
    tick = session.boundary_tick
    index = 0
    while session.boundary_tick == tick:
        index = _skip_regenerated_inputs(session, tick_inputs, index)
        if index < len(tick_inputs) and _input_is_injectable_now(
            session, tick_inputs[index]
        ):
            before = len(session.events.events)
            _inject_immediate(session, tick_inputs[index])
            _check_expected_suffix(session, expected, before)
            index += 1
            continue

        # Recorded automatic proposals may be the only policy representation of
        # a live RL model. Seed every currently missing inert RL context before a
        # poll, including proposals whose input positions are separated by the
        # derived decisions that the eventual commit will regenerate.
        _seed_recorded_rl_proposals(session, tick_inputs[index:])

        before_state = (
            len(session.events.events),
            session.phase,
            session.missing_context_ids,
            session.boundary_tick,
        )
        before_events = len(session.events.events)
        session.advance()
        _check_expected_suffix(session, expected, before_events)
        after_state = (
            len(session.events.events),
            session.phase,
            session.missing_context_ids,
            session.boundary_tick,
        )
        if after_state == before_state:
            next_input = (
                tick_inputs[index].get("event_id")
                if index < len(tick_inputs) else "end-of-tape"
            )
            raise ValueError(
                f"replay made no progress before {next_input} at boundary {tick}"
            )

    index = _skip_regenerated_inputs(session, tick_inputs, index)
    if index != len(tick_inputs):
        remaining = [
            event.get("event_id", event.get("global_sequence"))
            for event in tick_inputs[index:]
        ]
        raise ValueError(
            f"replay advanced boundary {tick} before inputs {remaining}"
        )


def _safe_terminal_advance(
    session: ControlledSimulationSession,
    expected: list[dict[str, Any]] | None,
) -> None:
    """Open or poll a terminal human boundary without ever crossing its tick."""
    probe = pickle.loads(pickle.dumps(session, protocol=5))
    probe_before = len(probe.events.events)
    probe_result = probe.advance()
    if probe_result.status != AWAITING_HUMAN:
        raise ValueError(
            "terminal expected events do not prove an open human pause; "
            "probe result is not an open human pause, refusing to cross until_tick"
        )
    if (
        len(probe.events.events) == probe_before
        and probe.missing_context_ids == session.missing_context_ids
        and probe.phase == session.phase
    ):
        raise ValueError("terminal human poll cannot regenerate the next tape event")
    before = len(session.events.events)
    result = session.advance()
    if result.status != AWAITING_HUMAN:
        raise RuntimeError("terminal human-pause probe diverged from live replay")
    _check_expected_suffix(session, expected, before)


def _drive_terminal_boundary(
    session: ControlledSimulationSession,
    tick_inputs: list[dict[str, Any]],
    expected: list[dict[str, Any]] | None,
) -> None:
    index = 0
    used_safe_advance = False
    while True:
        index = _skip_regenerated_inputs(session, tick_inputs, index)
        expected_complete = (
            expected is not None and len(session.events.events) == len(expected)
        )
        if index == len(tick_inputs) and (expected is None or expected_complete):
            break

        if index < len(tick_inputs) and _input_is_injectable_now(
            session, tick_inputs[index]
        ):
            before = len(session.events.events)
            _inject_immediate(session, tick_inputs[index])
            _check_expected_suffix(session, expected, before)
            index += 1
            continue

        _seed_recorded_rl_proposals(session, tick_inputs[index:])

        try:
            _safe_terminal_advance(session, expected)
        except ValueError as exc:
            remaining = [
                f"{event.get('event_type')}@{event.get('phase')}"
                for event in tick_inputs[index:]
            ]
            if any(_is_automatic_input(event) for event in tick_inputs[index:]):
                raise
            if remaining:
                raise ValueError(
                    f"unsupported input at terminal boundary "
                    f"{session.boundary_tick}: {remaining}"
                ) from exc
            raise
        used_safe_advance = True

    index = _skip_regenerated_inputs(session, tick_inputs, index)
    if index != len(tick_inputs):
        remaining = [
            f"{event.get('event_type')}@{event.get('phase')}"
            for event in tick_inputs[index:]
        ]
        raise ValueError(
            f"unsupported input at terminal boundary "
            f"{session.boundary_tick}: {remaining}"
        )
    if used_safe_advance and session.phase != AWAITING_HUMAN:
        raise ValueError("terminal replay must remain in an open human pause")


def replay_input_events(
    session: ControlledSimulationSession,
    input_events: Iterable[dict[str, Any]],
    *,
    until_tick: int,
    expected_events: Iterable[dict[str, Any]] | None = None,
) -> ControlledSimulationSession:
    """Re-run a session from its genesis state using only recorded inputs.

    Inputs are reinjected at their recorded ``boundary_tick`` and phase, in global
    sequence order.  Human queue and timeout ingress is recorded immediately;
    collection is a derived polling transition.  A terminal boundary is opened or
    polled only after a checkpoint clone proves the operation remains paused.
    """
    if isinstance(until_tick, bool) or not isinstance(until_tick, int) \
            or until_tick < session.boundary_tick:
        raise ValueError("until_tick must be an integer at or after the current boundary")
    expected_list = list(expected_events) if expected_events is not None else None
    inputs = sorted(
        (event for event in input_events if event.get("replay_class") == "input"),
        key=lambda event: int(event["global_sequence"]),
    )
    by_tick: dict[int, list[dict[str, Any]]] = {}
    for event in inputs:
        by_tick.setdefault(int(event["boundary_tick"]), []).append(event)

    while session.boundary_tick < until_tick:
        tick = session.boundary_tick
        _drive_advancing_boundary(
            session, by_tick.get(tick, []), expected_list,
        )

    _drive_terminal_boundary(
        session, by_tick.get(until_tick, []), expected_list,
    )

    session.events.verify()
    if expected_list is not None:
        expected = canonical_json(expected_list)
        actual = canonical_json(session.events.events)
        if actual != expected:
            raise ValueError("replayed canonical event stream differs from the source run")
    return session
